#' Generate operating characteristics for multiple simulations
#' 
#' Obtain the operating characteristics of the CFO-type and aCFO-type designs for multiple simulations.
#'
#' @usage CFO.oc(nsimu=5000, design, phi, p.true, ncohort, init.level, cohortsize,
#'        tau=NaN, accrual=NaN, tite.dist=NaN, accrual.dist=NaN, 
#'        add.args=list(alp.prior=phi, bet.prior=1-phi))
#'
#' @param nsimu the total number of trials to be simulated. The default value is 5000.
#' @param design option for selecting different designs, including CFO, aCFO, TITE-CFO, TITE-aCFO, fCFO, 
#'               f-aCFO, bCFO, and b-aCFO. Specifically, bCFO refers to the benchmark CFO, and b-aCFO 
#'               denotes the benchmark aCFO.
#' @param phi the target DLT rate.
#' @param p.true the true DLT rates under the different dose levels.
#' @param ncohort the total number of cohorts.
#' @param init.level the dose level assigned to the first cohort. The default value \code{init.level} is 1.
#' @param cohortsize the sample size in each cohort. 
#' @param tau maximal assessment window size. 'NaN' should be assigned if the design without late-oneset outcomes.
#' @param accrual the accrual rate, i.e., the number of patients accrued in tau time. 'NaN' should be assigned 
#'                if the design without late-oneset outcomes.
#' @param tite.dist the distribution of the time to DLT events. \code{tite.dist=1} corresponds to a uniform distribution, 
#'                  \code{tite.dist=2} corresponds to a Weibull distribution, and \code{tite.dist=3} corresponds to a 
#'                  log-logistic distribution. 'NaN' should be assigned if the design without late-oneset outcomes.
#' @param accrual.dist the distribution of the arrival times of patients. When \code{tite.dist=1}, it corresponds to all 
#'                     patients in each cohort arriving simultaneously at a given accrual rate. When \code{tite.dist=2}, 
#'                     it corresponds to a uniform distribution, and when \code{tite.dist=3}, it corresponds to an 
#'                     exponential distribution. 'NaN' should be assigned if the design without late-oneset outcomes.
#' @param add.args additional parameters, usually set as list(alp.prior=phi, bet.prior=1-phi) by default. \code{alp.prior} 
#'                 and \code{bet.prior} represent the parameters of the prior distribution for the true DLT rate at 
#'                 any dose level. This prior distribution is specified as Beta( \code{alpha.prior}, \code{beta.prior}).
#'
#' @details The operating characteristics of CFO-type and aCFO-type designs are generated by simulating trials under the 
#'          pre-specified true toxicity probabilities of the investigational doses. The choice of which design to execute 
#'          is determined by setting the \code{design} parameter. Some parameters (\code{tau}, \code{accrual}, 
#'          \code{tite.dist}, and \code{accrual.dist}) need to be set only when running a design that can handle late-onset 
#'          toxicities; otherwise, they default to NaN.\cr
#'          Additionally, in the example, we set \code{nsimu=100} for testing time considerations. In reality, \code{nsimu} 
#'          is typically set to 5000 to ensure the accuracy of the results.
#'
#' @return the \code{ CFO.oc() } function returns basic setup of ($simu.setup and $p.true) and the operating 
#'         characteristics ($selPercent and $simu.oc) of the design. \cr
#'         The operating characteristics includes \cr
#'         (1) selection percentage at each dose level ($selPercent) \cr
#'         (2) percentage of correct selection of the MTD ($simu.oc$MTDSel) \cr
#'         (3)percentage of patients allocated to the MTD ($simu.oc$MTDAllo) \cr
#'         (4)percentage of selecting a dose above the MTD ($simu.oc$overSel) \cr
#'         (5)percentage of allocating patients at dose levels above the MTD ($simu.oc$overAllo) \cr
#'         (6)percentage of the patients suffering DLT ($simu.oc$averDLT) \cr
#'         (7) Average trial duration if trials with late-onset toxicities ($simu.oc$averDur)
#' @importFrom dplyr transmute
#' @export
#'
#' @examples
#' nsimu <- 100; phi <- 0.2; ncohort <- 12; cohortsize <- 3; init.level <- 1
#' p.true <-c(0.01, 0.05, 0.10, 0.14, 0.20, 0.26, 0.34)
#' add.args=list(alp.prior=phi, bet.prior=1-phi)
#' ## get the operating characteristics for 100 simulations using the CFO design
#' CFO.oc (nsimu, design='CFO', phi, p.true, ncohort, init.level, cohortsize,
#'        tau=NaN, accrual=NaN, tite.dist=NaN, accrual.dist=NaN, add.args) 
#' ## get the operating characteristics for 100 simulations using the aCFO design
#' CFO.oc (nsimu, design='aCFO', phi, p.true, ncohort, init.level, cohortsize,
#'        tau=NaN, accrual=NaN, tite.dist=NaN, accrual.dist=NaN, add.args)
#' tau <- 3; accrual <- 6; tite.dist <- 2; accrual.dist <- 1
#' ## get the operating characteristics for 100 simulations using the TITE-CFO design
#' CFO.oc (nsimu, design='TITE-CFO', phi, p.true, ncohort, init.level, cohortsize,
#'         tau, accrual, tite.dist, accrual.dist, add.args) 
#' ## get the operating characteristics for 100 simulations using the TITE-aCFO design
#' CFO.oc (nsimu, design='TITE-aCFO', phi, p.true, ncohort, init.level, cohortsize,
#'         tau, accrual, tite.dist, accrual.dist, add.args)
#' ## get the operating characteristics for 100 simulations using the fCFO design
#' CFO.oc (nsimu, design='fCFO', phi, p.true, ncohort, init.level, cohortsize,
#'         tau, accrual, tite.dist, accrual.dist, add.args) 
#' ## get the operating characteristics for 100 simulations using the f-aCFO design
#' CFO.oc (nsimu, design='f-aCFO', phi, p.true, ncohort, init.level, cohortsize,
#'         tau, accrual, tite.dist, accrual.dist, add.args)
#' ## get the operating characteristics for 100 simulations using the bCFO design
#' CFO.oc (nsimu, design='bCFO', phi, p.true, ncohort, init.level, cohortsize,
#'         tau, accrual, tite.dist, accrual.dist, add.args) 
#' ## get the operating characteristics for 100 simulations using the b-aCFO design
#' CFO.oc (nsimu, design='b-aCFO', phi, p.true, ncohort, init.level, cohortsize,
#'         tau, accrual, tite.dist, accrual.dist, add.args) 
CFO.oc <- function(nsimu=5000, design, phi, p.true, ncohort, init.level, cohortsize,
                   tau=NaN, accrual=NaN, tite.dist=NaN, accrual.dist=NaN, 
                   add.args=list(alp.prior=phi, bet.prior=1-phi)){
  ###############################################################################
  ###############define the functions used for main function#####################
  ###############################################################################
  post.process.onemethod <- function(res, paras){
    tmtd <- paras$mtd
    target <- paras$target
    ndose <- length(paras$p.true)
    rv <- rep(0, 7)
    rv[1] <- sum(res$MTD==tmtd)
    rv[2] <- res$dose.ns[tmtd]
    if (res$MTD == 99){
      rv[3] <- 0
    }else{
      rv[3] <- sum(res$MTD>tmtd)
    }
    if (tmtd==ndose){
      rv[4] <- 0
    }else{
      rv[4] <- sum(res$dose.ns[(tmtd+1):ndose])
    }
    rv[5] <- sum((sum(res$DLT.ns)/sum(res$dose.ns))>target)
    rv[6] <- sum(res$DLT.ns)
    rv[7] <- sum(res$dose.ns)
    if (!is.null(res$total.time)){
      rv <- c(rv, res$total.time)
      names(rv) <- c(
        "MTD Sel", "MTD Allo", "Over Sel", 
        "Over Allo", "Risk of HT", "No DLT",
        "No Subject", "Duration")
    }else{
      names(rv) <- c(
        "MTD Sel", "MTD Allo", "Over Sel", 
        "Over Allo", "Risk of HT", "No DLT",
        "No Subject")
    }
    rv
    
  }
  
  post.process.single <- function(result){
    nMethod <- length(result)-1
    paras <- result$paras
    tmtd <- paras$mtd
    methods <- names(result)[1:nMethod]
    res.v <- list()
    for (name in methods){
      res.v[[name]] <- post.process.onemethod(result[[name]], paras)
    }
    do.call(rbind, res.v)
  }
  
  MTD.level <- function(phi, p.true){
    if (p.true[1]>phi+0.1){
      MTD <- 99
      return(MTD)
    }
    MTD <- which.min(abs(phi - p.true))
    return(MTD)
  }
  
  post.process <- function(results){
    MTD.Sel <- 0; MTD.Allo <- 0; Over.Sel <-0; Over.Allo <-0
    Risk.of.HT<-0; No.DLT<-0; Duration<-0; No.Subject<-0
    nsimu <- length(results)
    res.all <- 0
    for (result in results){
      res.all <- post.process.single(result) + res.all
    }
    res.all.df <- data.frame(res.all)
    if (is.null(res.all.df$Duration)){
      final.res <- dplyr::transmute(res.all.df, 
                                    MTD.Sel=MTD.Sel/nsimu,
                                    MTD.Allo=MTD.Allo/No.Subject,
                                    Over.Sel=Over.Sel/nsimu,
                                    Over.Allo=Over.Allo/No.Subject,
                                    Risk.of.HT=Risk.of.HT/nsimu,
                                    PerDLT=No.DLT/No.Subject
      )
    }else{
      final.res <- dplyr::transmute(res.all.df, 
                                    MTD.Sel=MTD.Sel/nsimu,
                                    MTD.Allo=MTD.Allo/No.Subject,
                                    Over.Sel=Over.Sel/nsimu,
                                    Over.Allo=Over.Allo/No.Subject,
                                    Risk.of.HT=Risk.of.HT/nsimu,
                                    PerDLT=No.DLT/No.Subject, 
                                    Duration=Duration/nsimu
      )
    }
    rownames(final.res) <- rownames(res.all.df)
    return(final.res)
  }
  
  ###############################################################################
  ############################MAIN DUNCTION######################################
  ###############################################################################  
  
  if (design == 'TITE-CFO'){accumulation = FALSE; impute.method = "TITE"
  }else if (design == 'fCFO'){accumulation = FALSE; impute.method = "frac"
  }else if (design == 'bCFO'){accumulation = FALSE; impute.method = "No"
  }else if (design == 'TITE-aCFO'){accumulation = TRUE; impute.method = "TITE"
  }else if (design == 'f-aCFO'){accumulation = TRUE; impute.method = "frac"
  }else if (design == 'b-aCFO'){accumulation = TRUE; impute.method = "No"
  }else if (design == 'CFO'){accumulation = FALSE; impute.method = NaN
  }else if (design == 'aCFO'){accumulation = TRUE; impute.method = NaN
  }
  run.fn <- function(i){
    set.seed(seeds[i])
    if (is.na(impute.method)){
      res <- aCFO.simu(phi, p.true, ncohort, init.level, cohortsize, add.args, accumulation)
    }else{
      res <- lateonset.simu(phi, p.true, tau, cohortsize, ncohort, accrual, tite.dist, accrual.dist, 
                            design, init.dose=1, add.args=list(alp.prior=phi, bet.prior=1-phi))
    }
    ress <- list(
      res=res,
      paras=list(p.true=p.true, 
                 mtd=tmtd, 
                 add.args=add.args,
                 target=phi,
                 ncohort=ncohort,
                 cohortsize=cohortsize)
    )
    return(ress)
  }
  
  seeds <- 1:nsimu
  
  tmtd <- MTD.level(phi, p.true)
  
  
  results <- lapply(1:nsimu, run.fn)
  results_nopara <- lapply(1:nsimu, function(i)results[[i]]$res)
  
  numTrials <- length(results_nopara)
  ndose <- length(results_nopara[[1]]$dose.ns)
  Perc <- rep(0, ndose)
  nonErrStops <- 0
  for (res in results_nopara){
    if (res$MTD != 99){
      nonErrStops <- nonErrStops + 1
      Perc[res$MTD] <- 1 + Perc[res$MTD]
    }
  }
  Perc <- Perc/numTrials
  errStop <- numTrials-nonErrStops
  
  sy <- post.process(results)
  
  if (is.na(impute.method)){
    res <- list(selPercent=Perc, p.true = p.true, errStop=errStop,
                simu.oc = data.frame(MTDSel=sy$MTD.Sel, MTDAllo=sy$MTD.Allo, 
                                     overSel=sy$Over.Sel, overAllo=sy$Over.Allo, averDLT=sy$PerDLT),
                simu.setup = data.frame(target = phi,ncohort = ncohort, 
                                        cohortsize = cohortsize, design = design, nsimu = nsimu))
    return(res)
  }else{
    res <- list(selPercent=Perc, p.true = p.true, errStop=errStop,
                simu.oc = data.frame(MTDSel=sy$MTD.Sel, MTDAllo=sy$MTD.Allo, overSel=sy$Over.Sel,
                                     overAllo=sy$Over.Allo, averDLT=sy$PerDLT, averDur = sy$Duration),
                simu.setup = data.frame(target = phi, ncohort = ncohort, 
                                        cohortsize = cohortsize, design = design, nsimu = nsimu))
    return(res)
  }
}
